"""`decisions index` — mechanically regenerate `wiki/decisions.md` from
`decisions/**/*.md` frontmatter. Never hand-edited, so it can't go stale.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from sleeper_agent.wiki_tools.frontmatter import parse_page

HEADER = "# Decision log index\n\nMechanically generated by `decisions index` — do not hand-edit.\n"


@dataclass(frozen=True)
class DecisionEntry:
    path: Path
    date: str
    kind: str
    season: str
    status: str


def collect_decisions(decisions_dir: Path) -> list[DecisionEntry]:
    entries: list[DecisionEntry] = []
    if not decisions_dir.exists():
        return entries
    for path in sorted(decisions_dir.rglob("*.md")):
        page = parse_page(path.read_text())
        entries.append(
            DecisionEntry(
                path=path,
                date=str(page.frontmatter.get("date", "")),
                kind=str(page.frontmatter.get("kind", "")),
                season=str(page.frontmatter.get("season", "")),
                status=str(page.frontmatter.get("status", "")),
            )
        )
    return sorted(entries, key=lambda e: (e.date, e.path.name))


def render_index(
    entries: list[DecisionEntry], decisions_dir: Path, wiki_dir: Path
) -> str:
    lines = [HEADER]
    for entry in entries:
        relative = Path("..") / entry.path.relative_to(wiki_dir.parent)
        lines.append(
            f"- {entry.date} [{entry.kind}] season {entry.season} ({entry.status}): "
            f"[{entry.path.stem}]({relative.as_posix()})"
        )
    return "\n".join(lines) + "\n"


def build_index(decisions_dir: Path, wiki_dir: Path) -> Path:
    entries = collect_decisions(decisions_dir)
    content = render_index(entries, decisions_dir, wiki_dir)
    index_path = wiki_dir / "decisions.md"
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(content)
    return index_path
